### ISSUE TITLE
bgpreader of v2beta returns error (librdkafka version issue)

### ISSUE THREAD

**Issue by a16** [CAIDA/libbgpstream#51]
Hello,

I'm interested in `public live BMP stream` and have found this page.
https://bgpstream.caida.org/v2-beta#bmp
Then following the above, I tried it with bgpreader. but it failed with the errors below.
Of course, it also failed with pybgpstream(2.0.0). 

```bash
% bgpreader -d beta-bmp-stream
WARN: No time windows specified, defaulting to all available data
2018-08-25 01:51:42 24707: bs_transport_kafka.c:163: ERROR: Config Error: No such configuration property: "auto.offset.reset"
2018-08-25 01:51:42 24707: bs_transport_kafka.c:241: ERROR: Could not create Kafka consumer config
2018-08-25 01:51:42 24707: bgpstream_transport.c:95: ERROR: Could not open resource (bmp.bgpstream.caida.org)
2018-08-25 01:51:42 24707: bgpstream_reader.c:164: WARNING: Could not open (bmp.bgpstream.caida.org). Attempt 1 of 5
2018-08-25 01:51:52 24707: bs_transport_kafka.c:163: ERROR: Config Error: No such configuration property: "auto.offset.reset"
--- snip ---
```
How can I set `auto.offset.reset` in bgpreader/pybgpstream?

**Comment by alistairking** [comment]
Thanks for giving v2 a try!

My guess is that this is because you have an old version of librdkafka. Can you try installing the latest version (https://github.com/edenhill/librdkafka/releases/tag/v0.11.5) and see if that helps?

**Comment by a16** [comment]
Used 0.9.3 on debian(stretch). It works fine after upgraded to 0.11.5.
Thanks!

**Comment by alistairking** [comment]
thanks for the report. i'll leave this issue open to remind us to try and add some better detection of librdkafka version or at least some better error messages.

**Comment by alistairking** [comment]
Fixed by #153
